### ISSUE TITLE
Proposed tree hashing test suite format

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/eth2.0-tests#11]
In addition to [plain SSZ tests](https://github.com/ethereum/eth2.0-tests/issues/8), we need standardized tests for the related tree hashing algorithm following the [general test format](https://github.com/ethereum/eth2.0-specs/blob/master/specs/test-format.md). Proposed format:

### Test suite name

`tree_hashing`

### Test case format

```YAML
type: <type def string>
value: <value to hash>
result: <tree hash>
```

For type and value definition, we use the same format as in the SSZ tests.

The result is encoded as hex with a `0x` prefix.

### Example

```YAML
title: uint tree hashing
test_suite: tree_hashing
fork: all
version: "0.1"

test_cases:

- type: uint8
  value: 0
  result: "0x0000000000000000000000000000000000000000000000000000000000000000"

- type: uint384
  value: 0
  result: "0xc980e59163ce244bb4bb6211f48c7b46f88a4f40943e84eb99bdc41e129bd293"
```
